name: Build EOL Rubies

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  transpile:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: Transpile Ruby Next
      run: |
        bundle exec rake nextify
    - name: Store transpiled files
      uses: actions/upload-artifact@v2
      with:
        name: ruby-next-transpiled
        path: lib/.rbnext
        if-no-files-found: ignore

  build:
    needs: transpile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.3, 2.4, 2.5, 2.6]
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_GEMFILE: gemfiles/eol.gemfile
      # To avoid installing ruby-next with all the transpiling deps
      RELEASING_PACO: true
      CI: true
      EOL: true
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 1.17
        bundler-cache: true
    - name: Restore transpiled files
      uses: actions/download-artifact@v2
      with:
        name: ruby-next-transpiled
        path: lib/.rbnext
    - name: Run RSpec
      run: bundle exec rspec
